export const imagePath = {
    splashBackground: require('../Images/splashBackground.png'),
    splashBG: require('../Images/splashBG.jpg'),
    appLogo: require('../Images/appLogo.png'),
    introImage: require('../Images/IntroImage.png'),
    facebookIcon: require('../Images/facebookIcon.png'),
    gmailIcon: require('../Images/gmail.png'),
    appleIcon: require('../Images/apple.png'),
    landingPageImage: require('../Images/LandingPageImage.png'),
    landingPage1: require('../Images/landingPage1.png'),
    landingPage2: require('../Images/landingPage2.png'),
    americanFoodImage: require('../Images/americanFood.png'),
    addIcon: require('../Images/addIcon.png'),
    filledStar: require('../Images/filledStar.png'),
    likedPost: require('../Images/liked.png'),
    unlikedPost: require('../Images/unliked.png'),
    commentImage: require('../Images/comment.png'),
    restaurantBG: require('../Images/restaurantBG.png'),
    dummyProfile: require('../Images/dummyProfile.jpg'),
    darkSplashBG: require('../Images/darkSplashBG.png'),
    darkRestaurantBG: require('../Images/darkRestaurantBG.png'),
    quarterStar: require('../Images/1_4.png'),
    halfStar: require('../Images/1_2.png'),
    threeQuarterStar: require('../Images/3_4.png'),
    emptyStar: require('../Images/emptyStar.png'),
    fullStar: require('../Images/4_4.png')
}